# Generated by Django 5.0.4 on 2024-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('descripcion', models.TextField(blank=True)),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
    ]
